// Generated by https://quicktype.io

export class ViewFinanceiro {
    id: number;
    dtCriacao: Date;
    igrejaId: number;
    idAssinatura: number;
    numeroCobranca: number;
    linkBoleto: string;
    dataVencimento: Date;
    tolerancia: number;
    statusPagamento: number;
}
