export enum Endpoint {
    Token = '/Token',
    ResetSenha = '/Token/resetSenha',
    Igreja = '/Igreja',
    Usuario = '/Usuarios',
    Pastores = '/Pastores',
    Pessoa = '/Pessoa',
    Membros = '/Membros',
    Filhos = '/Filhos',
    Obreiro = '/Obreiro',
    HistoricoObreiro = '/HistoricoObreiro',
    BuscaPorCpf = '/Pessoa/buscaPorCpf',
    Enderecos = '/Enderecos',
    Contatos = '/Contatos',
    Cargos = '/Cargos',
    Ofertas = '/Ofertas',  
    Relatorios = '/Relatorios',
    RelatoriosFichaMembro = '/Relatorios/FichaMembro',
    RelatoriosCartas = '/Relatorios/Cartas',
    UploadArquivo = '/File/FotoPerfil',
    RemoverFotoperfil = '/File/FotoPerfilRemover',
    ServiceCenter = '/ServiceCenter',
    DownloadArquivo = '/File/DownloadArquivo',
    cep = 'https://viacep.com.br/ws/{0}/json',
}