export enum Endpoint {
    Token = '/Token',
    Usuario = '/Usuarios',
    Pessoa = '/Pessoa',
    Membros = '/Membros',
    Obreiro = '/Obreiro',
    HistoricoObreiro = '/HistoricoObreiro',
    BuscaPorCpf = '/Pessoa/buscaPorCpf',
    Enderecos = '/Enderecos',
    Contatos = '/Contatos',
    Cargos = '/Cargos',
    Ofertas = '/Ofertas',  
    Relatorios = '/Relatorios',
    RelatoriosFichaMembro = '/Relatorios/FichaMembro',
    UploadArquivo = '/File/FotoPerfil',
    RemoverFotoperfil = '/File/FotoPerfilRemover',
    DownloadArquivo = '/File/DownloadArquivo',
    cep = 'https://viacep.com.br/ws/{0}/json',

}